Added contact form
adeola003/Microverse_portfolio pull request #3
Opened 2023-02-21 17:00 UTC by adeola003

To achieve the expected result, I have been through the following steps:
1. I opened the previous project;
2. I created a new branch named "add_contact_form";
3. I created a new section for the form in my HTML file;
4. I added the form and then styled it in CSS trying to match as much as possible with the template.

2023-02-21 17:14 UTC, osamaashraf6 reviewed
Hi @adeola003 😊, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🆘💀

- You have submitted a project, that no partners contributed at the project, so everyone has contributed to the project to make the pull request valid, so kindly try to make your partner a collaborator and let him/her write a commit with you at the pull request and with that the pull request will be valid 😃

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-02-22 10:24 UTC, Shedrack-Sunday requested changes
Hi @adeola003 @Atifzada    👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done well implementing the requirements,  However, there are a few you need to work on, to move to the next project. 💯

 
![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)


Highlights
✅All linters are checked
✅ Descriptive commit messages 
  
Required Changes ♻️

- [x] The slight change needed has to do with a bit of styling of the buttons.

_check the comment section for a detailed review_ 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-02-22 10:24 UTC, Shedrack-Sunday commented on index.html
> +      <ul>
- [ ] Nice work you did so far 👏 . However, Kindly use flexbox to layout elements of the form filed. This give you extra flexibility 👍 

## Instructions :
![image](https://user-images.githubusercontent.com/50990925/220591752-03103517-3a1b-49b1-9941-fb2e6961acf7.png)

2023-02-22 10:24 UTC, Shedrack-Sunday commented on index.html
> +        </li>
- [ ] With refrence to the figma design, kindly, adjust the styling of your button, to look same as that given below ;:
## Your design:
![image](https://user-images.githubusercontent.com/50990925/220591305-bf3da3b9-df05-4546-8688-45060d72aaeb.png)

## Figma:
![image](https://user-images.githubusercontent.com/50990925/220591464-85cecf53-55b8-412b-8319-62d34925ca32.png)

2023-02-22 10:24 UTC, Shedrack-Sunday commented on style.css
> +  transition-duration: 0.4s;
- [ ] Kindly adhere to the hover color pattern given , as your current reactions does not tally with the template olors below :

## The hover colors:
![image](https://user-images.githubusercontent.com/50990925/220592723-8772b2a3-bcf3-4d56-b7f7-e6a7c16d89ad.png)

2023-02-22 11:41 UTC, roshan-bajgain approved these changes
Hi @adeola003, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-22 11:53 UTC, merged